## Add env variables to the docker compose file
version: '3'

services:
  code-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.code-server
    ports:
      - "8080:8080"
      - "8081:8081"
  
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    ports:
      - "9091:9091"
    depends_on:
      - postgres
    environment:
      - Gemini_API_KEY="AIzaSyAHrcp4Hx1X6XzrL1wKHU2YWPn7agHEvjQ"
      - WS_RELAYER_URL=ws://ws-relayer:9093
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
  
  ws-relayer:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws-relayer
    environment:
      - WS_RELAYER_URL=ws://ws-relayer:9093
    depends_on:
      - postgres
  
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.primary-backend
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/nextdb
      - GOOGLE_CLIENT_ID=367282788470-fsbb4f3ps8fbnma6ugndrmfrl1gblqsr.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=http://localhost:9090/api/v1/auth/google/callback
      - JWT_SECRET=secret
      - FRONTEND_URL=http://localhost:3000
      - GITHUB_CLIENT_ID=Iv23lixMN0zX8MYILghd
      - GITHUB_CLIENT_SECRET=0ef21d8d7c5eb7179ddeb4df7ee97aeaab6e9f85
      - GITHUB_CALLBACK_URL=http://localhost:8080/api/v1/auth/github/callback

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
      - CLERK_SECRET_KEY=
    volumes:
      - ./apps/frontend:/app/apps/frontend

volumes:
  postgres_data:
